### ISSUE TITLE
Unexpected value 'GalleryModal' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by kapil-kumawat** [nikini/ionic-gallery-modal#12]
Unexpected value 'GalleryModal' declared by the module 'AppModule'
when compile with
ionic build android --prod --release

**Comment by kapil-kumawat** [comment]
this is my app.module.ts file code :

import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { GalleryModal } from 'ionic-gallery-modal';
import { ZoomableImage } from 'ionic-gallery-modal';
@NgModule({  
declarations: [
    MyApp,
    HomePage, 
  GalleryModal,
 ZoomableImage],  
imports: [
    IonicModule.forRoot(MyApp)
  ],  
bootstrap: [IonicApp],  
entryComponents: [
    MyApp,
    HomePage, 
      GalleryModal 
  ],  
providers: [{provide: ErrorHandler, useClass: IonicErrorHandler}]
})
export class AppModule {}

**Comment by davideas** [comment]
It occurs also to me, @nikini will you resolve this?
Also, could you check if this module needs to be adapted for latest version Ionic?

**Comment by Rieranthony** [comment]
Same for me, someone found any solutions?

**Comment by nikini** [comment]
I don't have the time for it and I won't have it in the next few weeks. I can help you understand things through the code and you can debug it

**Comment by JoelAH** [comment]
I need a solution also

**Comment by ridwan85** [comment]
Download or clone the source from this repo.
Create appmodule folder in your src
You would have something like this
```
app
   app.component.ts
   app.html
   app.module.ts
   app.scss
   main.ts
appmodule <----new folder
   gallery-modal     ///all files from the repo 
   zoomable-image
   interfaces
```
And then in your app.module.ts file

instead of
```
import { GalleryModal } from 'ionic-gallery-modal';
import { ZoomableImage } from 'ionic-gallery-modal';
```
change to this

```
import { GalleryModal } from '../appmodule/gallery-modal/gallery-modal';
import { ZoomableImage } from '../appmodule/zoomable-image/zoomable-image';
```

And in any of your pages/yourfile.ts

just import this to use it.
```
import { GalleryModal } from '../../appmodule/gallery-modal/gallery-modal';
import { ZoomableImage } from '../../appmodule/zoomable-image/zoomable-image';
```
Then run 
`ionic build ios --prod`
or
`ionic build android --prod`

The problem should go away. Somehow i think this issue related to this [https://github.com/angular/angular-cli/issues/1831](https://github.com/angular/angular-cli/issues/1831) 

But above is my workaround. Hope it helps anyone facing the same problem.

**Comment by nikini** [comment]
Can you try version 0.1.0 and tell me if this still happens?
